import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  preflight: true,
  include: ['./pages/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  exclude: [],
  jsxFramework: 'react',
  outdir: 'styled-system',
  globalCss: {
    ':root': {
      colorScheme: 'dark',
      '--bg': '#050814',
      '--bg-2': '#070b18',
      '--panel': 'rgba(16, 27, 52, 0.76)',
      '--panel-strong': 'rgba(20, 34, 66, 0.92)',
      '--line': 'rgba(143, 177, 255, 0.22)',
      '--text': '#eef5ff',
      '--muted': '#aebdd7',
      '--brand': '#36f1cd',
      '--brand-strong': '#9dffe9',
      '--hot': '#ff4d8d',
      '--warn': '#ffd166',
      '--ink-on-brand': '#04110f',
      '--header-bg': 'rgba(5, 8, 20, 0.78)',
      '--footer-bg': 'rgba(5, 8, 20, 0.82)',
      '--shadow': '0 30px 100px rgba(0, 0, 0, 0.45)',
      '--soft-shadow': '0 18px 60px rgba(0, 0, 0, 0.24)',
      '--content-width': '1180px',
      '--font-sans': '"Noto Sans KR", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", "Segoe UI", sans-serif',
      fontFamily: 'var(--font-sans)',
    },
    ':root[data-theme="light"]': {
      colorScheme: 'light',
      '--bg': '#f7fbff',
      '--bg-2': '#eef5ff',
      '--panel': 'rgba(255, 255, 255, 0.78)',
      '--panel-strong': 'rgba(255, 255, 255, 0.94)',
      '--line': 'rgba(41, 66, 112, 0.16)',
      '--text': '#101728',
      '--muted': '#526078',
      '--brand': '#008f7c',
      '--brand-strong': '#0ecfb2',
      '--hot': '#c62d68',
      '--warn': '#916300',
      '--ink-on-brand': '#f8fffd',
      '--header-bg': 'rgba(247, 251, 255, 0.82)',
      '--footer-bg': 'rgba(247, 251, 255, 0.9)',
      '--shadow': '0 30px 100px rgba(46, 73, 120, 0.22)',
      '--soft-shadow': '0 18px 60px rgba(46, 73, 120, 0.14)',
    },
    html: { scrollBehavior: 'smooth' },
    body: {
      margin: '0',
      minWidth: '320px',
      minHeight: '100vh',
      overflowX: 'hidden',
      background: 'radial-gradient(circle at top left, color-mix(in srgb, var(--brand) 22%, transparent), transparent 34rem), radial-gradient(circle at 78% 20%, color-mix(in srgb, var(--hot) 18%, transparent), transparent 30rem), linear-gradient(180deg, var(--bg) 0%, var(--bg-2) 48%, var(--bg) 100%)',
      color: 'var(--text)',
      fontFamily: 'var(--font-sans)',
      lineHeight: '1.68',
      letterSpacing: '-0.012em',
      wordBreak: 'keep-all',
      textWrap: 'pretty',
      WebkitFontSmoothing: 'antialiased',
      textRendering: 'optimizeLegibility',
    },
    a: { color: 'inherit', textDecoration: 'none' },
    'button, input, textarea, select': { font: 'inherit' },
    'h1, h2, h3, p': { marginTop: '0' },
    '@keyframes cube-float': {
      '0%, 100%': { transform: 'rotateX(-18deg) rotateY(34deg) translate3d(0, 0, 0)' },
      '50%': { transform: 'rotateX(-10deg) rotateY(52deg) translate3d(0, -12px, 0)' },
    },
    '@keyframes orbit-spin': {
      to: { rotate: '360deg' },
    },
    '@media (prefers-reduced-motion: reduce)': {
      html: { scrollBehavior: 'auto' },
      '*, *::before, *::after': {
        animationDuration: '.001ms !important',
        animationIterationCount: '1 !important',
        transitionDuration: '.001ms !important',
      },
    },
  },
});
