import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  preflight: true,
  include: ['./pages/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  exclude: [],
  jsxFramework: 'react',
  outdir: 'styled-system',
  globalCss: {
    ':root': {
      colorScheme: 'dark',
      '--bg': '#11110f',
      '--bg-2': '#181713',
      '--panel': 'rgba(245, 240, 231, 0.055)',
      '--panel-strong': 'rgba(245, 240, 231, 0.095)',
      '--line': 'rgba(245, 240, 231, 0.16)',
      '--text': '#f5f0e7',
      '--muted': '#b8afa0',
      '--brand': '#ff4e57',
      '--brand-strong': '#ff745f',
      '--brand-deep': '#592025',
      '--accent-red': '#ff4e57',
      '--accent-yellow': '#ffd65a',
      '--accent-green': '#83ff73',
      '--accent-blue': '#7cc8ff',
      '--ink-on-brand': '#17110f',
      '--header-bg': 'rgba(17, 17, 15, 0.82)',
      '--footer-bg': 'rgba(17, 17, 15, 0.9)',
      '--shadow': '0 34px 100px rgba(0, 0, 0, 0.34)',
      '--soft-shadow': '0 16px 42px rgba(0, 0, 0, 0.2)',
      '--content-width': '1210px',
      '--radius-lg': '1rem',
      '--radius-xl': '1.35rem',
      '--font-sans': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", "Segoe UI", sans-serif',
      fontFamily: 'var(--font-sans)',
    },
    ':root[data-theme="light"]': {
      colorScheme: 'light',
      '--bg': '#f3efe6',
      '--bg-2': '#e8e1d4',
      '--panel': 'rgba(22, 20, 17, 0.045)',
      '--panel-strong': 'rgba(22, 20, 17, 0.075)',
      '--line': 'rgba(22, 20, 17, 0.16)',
      '--text': '#171410',
      '--muted': '#625a4f',
      '--brand': '#d83b43',
      '--brand-strong': '#f05b45',
      '--brand-deep': '#ffd5cc',
      '--accent-red': '#d62f3b',
      '--accent-yellow': '#9d7100',
      '--accent-green': '#207a29',
      '--accent-blue': '#136fa5',
      '--ink-on-brand': 'rgb(255 248 239)',
      '--header-bg': 'rgba(243, 239, 230, 0.86)',
      '--footer-bg': 'rgba(243, 239, 230, 0.92)',
      '--shadow': '0 34px 100px rgba(22, 20, 17, 0.16)',
      '--soft-shadow': '0 16px 42px rgba(22, 20, 17, 0.11)',
    },
    '*, *::before, *::after': { boxSizing: 'border-box' },
    html: {
      width: '100%',
      maxWidth: '100vw',
      overflowX: 'clip',
      scrollBehavior: 'smooth',
    },
    body: {
      margin: '0',
      minWidth: '0',
      width: '100%',
      maxWidth: '100vw',
      minHeight: '100dvh',
      overflowX: 'clip',
      overflowWrap: 'break-word',
      background:
        'linear-gradient(rgba(245,240,231,.045) 1px, transparent 1px), linear-gradient(90deg, rgba(245,240,231,.04) 1px, transparent 1px), radial-gradient(circle at 72% -10%, color-mix(in srgb, var(--brand) 18%, transparent), transparent 30rem), linear-gradient(180deg, var(--bg) 0%, var(--bg-2) 48%, var(--bg) 100%)',
      backgroundSize: '42px 42px, 42px 42px, auto, auto',
      color: 'var(--text)',
      fontFamily: 'var(--font-sans)',
      lineHeight: '1.68',
      letterSpacing: '-0.012em',
      wordBreak: 'keep-all',
      textWrap: 'pretty',
      WebkitFontSmoothing: 'antialiased',
      textRendering: 'optimizeLegibility',
    },
    'img, svg, canvas, video': {
      maxWidth: '100%',
    },
    '::selection': {
      color: 'var(--ink-on-brand)',
      background: 'var(--brand)',
    },
    a: { color: 'inherit', textDecoration: 'none' },
    'button, input, textarea, select': { font: 'inherit' },
    'h1, h2, h3, p': { marginTop: '0' },
    '@media (prefers-reduced-motion: reduce)': {
      html: { scrollBehavior: 'auto' },
      '*, *::before, *::after': {
        animationDuration: '.001ms !important',
        animationIterationCount: '1 !important',
        transitionDuration: '.001ms !important',
      },
    },
  },
});
