import { css } from '../../styled-system/css';

const mutedText = {
  color: 'var(--muted)',
  lineHeight: '1.78',
};

const pillAction = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: '3rem',
  padding: '.86rem 1.18rem',
  borderRadius: '999px',
  border: '1px solid var(--line)',
  fontWeight: '850',
  lineHeight: '1.2',
  whiteSpace: 'nowrap',
  transition: 'transform .2s cubic-bezier(.16,1,.3,1), border-color .2s ease, background .2s ease',
  _hover: { transform: 'translateY(-2px)' },
  _active: { transform: 'translateY(1px) scale(.99)' },
  _focusVisible: {
    outline: 'none',
    boxShadow: '0 0 0 4px color-mix(in srgb, var(--brand) 20%, transparent)',
  },
  '@media (max-width: 520px)': { width: '100%' },
};


export const homeStyles = {
  main: css({
    position: 'relative',
    width: '100%',
    maxWidth: '1440px',
    minWidth: '0',
    margin: '0 auto',
    paddingInline: 'clamp(.75rem, 2vw, 2rem)',
    '@media (max-width: 760px)': { width: '100%', paddingInline: '.75rem' },
  }),
  scrollStage: css({
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '0',
    alignItems: 'start',
    minHeight: '560dvh',
    padding: '0 0 clamp(4rem, 9vw, 7rem)',
    isolation: 'isolate',
    minWidth: '0',
    '@media (max-width: 980px)': {
      gridTemplateColumns: '1fr',
      minHeight: 'auto',
      paddingTop: '2.5rem',
    },
  }),
  storyFlow: css({
    position: 'relative',
    display: 'grid',
    gridColumn: '1',
    gridRow: '1',
    zIndex: '3',
    pointerEvents: 'none',
    paddingInline: 'clamp(1rem, 4vw, 4.2rem)',
    minWidth: '0',
    '@media (max-width: 980px)': {
      gridColumn: 'auto',
      gridRow: 'auto',
      order: '1',
      gap: '1rem',
      paddingInline: '0',
      pointerEvents: 'auto',
    },
  }),
  stageAura: css({
    position: 'absolute',
    inset: '-10rem -12vw auto',
    height: '48rem',
    pointerEvents: 'none',
    background: 'transparent',
    filter: 'none',
    opacity: '0',
    zIndex: '-1',
  }),
  sceneRail: css({
    position: 'sticky',
    top: '4.5rem',
    gridColumn: '1',
    gridRow: '1',
    alignSelf: 'start',
    display: 'grid',
    height: 'calc(100dvh - 4.5rem)',
    minHeight: 'calc(100dvh - 4.5rem)',
    zIndex: '2',
    minWidth: '0',
    '@media (max-width: 980px)': {
      position: 'relative',
      top: 'auto',
      gridColumn: 'auto',
      gridRow: 'auto',
      order: '0',
      height: 'clamp(22rem, 66vw, 34rem)',
      minHeight: 'auto',
    },
    '@media (max-width: 520px)': { height: '21rem' },
  }),
  sideRailLeft: css({
    display: 'grid',
    gridColumn: '1',
    gridRow: '1',
    gap: '0',
    padding: '0 0 70dvh',
    alignContent: 'start',
    zIndex: '3',
    '@media (max-width: 980px)': {
      order: '1',
      gap: '1rem',
      padding: '0',
    },
  }),
  sideRailRight: css({
    display: 'grid',
    gridColumn: '3',
    gridRow: '1',
    gap: '0',
    padding: '92dvh 0 42dvh',
    alignContent: 'start',
    zIndex: '3',
    '@media (max-width: 980px)': {
      order: '2',
      gap: '1rem',
      padding: '0',
    },
  }),
  heroCopy: css({
    display: 'grid',
    alignContent: 'center',
    justifySelf: 'start',
    width: 'min(27rem, 31vw)',
    minHeight: 'calc(100dvh - 4.5rem)',
    padding: 'clamp(1rem, 2.4vw, 1.5rem) .25rem',
    borderRadius: '0',
    border: '1px solid transparent',
    background: 'transparent',
    pointerEvents: 'auto',
    '@media (max-width: 980px)': {
      width: '100%',
      minHeight: 'auto',
      paddingTop: '1.25rem',
    },
  }),
  h1: css({
    maxWidth: '13ch',
    marginBottom: '1.15rem',
    fontSize: 'clamp(2.65rem, 5vw, 5rem)',
    fontWeight: '760',
    lineHeight: '1.02',
    letterSpacing: '-.06em',
    textWrap: 'balance',
    '& span': {
      display: 'block',
      color: 'transparent',
      background: 'linear-gradient(90deg, var(--brand), var(--accent-yellow))',
      backgroundClip: 'text',
    },
    '@media (max-width: 760px)': {
      maxWidth: '100%',
      fontSize: 'clamp(2.35rem, 11.5vw, 4.15rem)',
      lineHeight: '1.05',
    },
  }),
  heroText: css({
    ...mutedText,
    maxWidth: '34rem',
    marginBottom: '0',
    fontSize: 'clamp(1rem, 1.8vw, 1.13rem)',
  }),
  motionCommand: css({
    display: 'grid',
    gap: '.45rem',
    width: 'fit-content',
    marginTop: '1.45rem',
    padding: '.78rem .9rem',
    border: '1px solid color-mix(in srgb, var(--brand) 28%, var(--line))',
    borderRadius: '.82rem',
    background:
      'linear-gradient(135deg, color-mix(in srgb, var(--brand) 12%, transparent), color-mix(in srgb, var(--accent-yellow) 6%, transparent)), color-mix(in srgb, var(--bg) 68%, transparent)',
    boxShadow: 'inset 0 1px rgba(245,240,231,.08)',
    '& span': {
      color: 'var(--muted)',
      fontSize: '.68rem',
      fontWeight: '850',
      letterSpacing: '.18em',
      lineHeight: '1.1',
      textTransform: 'uppercase',
    },
    '& code': {
      color: 'var(--text)',
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      fontSize: '.9rem',
      letterSpacing: '-.02em',
      whiteSpace: 'nowrap',
    },
    '@media (max-width: 520px)': {
      width: '100%',
      '& code': { whiteSpace: 'normal' },
    },
  }),
  actionRow: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: '.85rem',
    marginTop: '1.75rem',
  }),
  buttonPrimary: css({
    ...pillAction,
    borderColor: 'transparent',
    color: 'var(--ink-on-brand)',
    background: 'linear-gradient(135deg, var(--brand), var(--brand-strong))',
  }),
  buttonGhost: css({
    ...pillAction,
    color: 'var(--text)',
    background: 'transparent',
  }),
  storyPanel: css({
    position: 'relative',
    display: 'grid',
    alignContent: 'center',
    justifySelf: 'start',
    width: 'min(24rem, 27vw)',
    minHeight: '100dvh',
    padding: 'clamp(1rem, 2.2vw, 1.35rem) .25rem',
    borderRadius: '0',
    border: '0',
    overflow: 'visible',
    background: 'transparent',
    pointerEvents: 'auto',
    '& h2': {
      maxWidth: '9.4ch',
      marginBottom: '1rem',
    },
    '& p': {
      ...mutedText,
      maxWidth: '32rem',
      marginBottom: '0',
      fontSize: '1.02rem',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: '50%',
      width: 'clamp(2.5rem, 10vw, 9rem)',
      height: '2px',
      background: 'linear-gradient(90deg, transparent, var(--brand), transparent)',
      pointerEvents: 'none',
    },
    '&[data-side=left]::after': { right: 'calc(-1 * clamp(2rem, 8vw, 7rem))' },
    '&[data-side=right]': {
      justifySelf: 'end',
      textAlign: 'right',
      '& p': { marginLeft: 'auto' },
    },
    '&[data-side=right]::after': { left: 'calc(-1 * clamp(2rem, 8vw, 7rem))' },
    '@media (max-width: 980px)': {
      width: '100%',
      minHeight: 'auto',
      padding: '1rem 0',
      textAlign: 'left',
      '&[data-side=right] p': { marginLeft: '0' },
      '&::after': { display: 'none' },
    },
  }),
  storyTone: css({
    display: 'inline-flex',
    width: 'fit-content',
    marginBottom: '1.1rem',
    color: 'var(--brand)',
    fontSize: '.78rem',
    fontWeight: '850',
    letterSpacing: '.08em',
    textTransform: 'uppercase',
  }),
  h2: css({
    fontSize: 'clamp(2rem, 4.4vw, 3.65rem)',
    fontWeight: '720',
    lineHeight: '1.05',
    letterSpacing: '-.045em',
    textWrap: 'balance',
    '@media (max-width: 760px)': { lineHeight: '1.12' },
  }),
  h3: css({
    fontSize: 'clamp(1.22rem, 2vw, 1.55rem)',
    fontWeight: '720',
    lineHeight: '1.3',
    letterSpacing: '-.02em',
    textWrap: 'balance',
  }),
  metrics: css({
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '0',
    margin: '0 0 clamp(3rem, 6vw, 5rem)',
    borderTop: '1px solid var(--line)',
    borderBottom: '1px solid var(--line)',
    '& article': {
      minHeight: '7rem',
      padding: '1rem',
      borderRight: '1px solid var(--line)',
      transition: 'transform .2s ease, border-color .2s ease',
    },
    '& article:last-child': { borderRight: '0' },
    '& strong, & span': { display: 'block' },
    '& strong': { color: 'var(--text)', fontSize: '1.06rem', lineHeight: '1.35' },
    '& span': { color: 'var(--muted)', marginTop: '.45rem', fontSize: '.94rem', lineHeight: '1.55' },
    '@media (max-width: 980px)': {
      gridTemplateColumns: 'repeat(2, 1fr)',
      '& article:nth-child(2)': { borderRight: '0' },
      '& article:nth-child(-n + 2)': { borderBottom: '1px solid var(--line)' },
    },
    '@media (max-width: 620px)': {
      gridTemplateColumns: '1fr',
      '& article': { borderRight: '0', borderBottom: '1px solid var(--line)' },
      '& article:last-child': { borderBottom: '0' },
    },
  }),
  motionStrip: css({
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '0',
    margin: '0 0 clamp(3.5rem, 7vw, 5.5rem)',
    borderTop: '1px solid var(--line)',
    '& article': {
      position: 'relative',
      display: 'grid',
      gridTemplateColumns: 'minmax(11rem, .32fr) 1fr',
      gap: 'clamp(1rem, 4vw, 3rem)',
      minHeight: 'auto',
      padding: '1.05rem 0',
      borderBottom: '1px solid var(--line)',
      borderRadius: '0',
      overflow: 'hidden',
      background: 'transparent',
    },
    '& article::before': {
      content: '""',
      position: 'absolute',
      inset: '50% 0 auto auto',
      width: '2.5rem',
      aspectRatio: '1',
      borderRadius: '999px',
      border: '1px solid color-mix(in srgb, var(--brand) 34%, transparent)',
      background:
        'conic-gradient(from 110deg, var(--accent-red), transparent 18%, var(--accent-yellow) 24%, transparent 38%, var(--accent-green) 46%, transparent 68%, var(--brand) 84%, transparent)',
      opacity: '.42',
      transform: 'translateY(-50%)',
    },
    '& span': {
      display: 'block',
      color: 'var(--brand)',
      fontSize: '.78rem',
      fontWeight: '900',
      letterSpacing: '.1em',
      lineHeight: '1.2',
      textTransform: 'uppercase',
    },
    '& p': {
      position: 'relative',
      margin: '0',
      color: 'var(--muted)',
      fontSize: '.94rem',
      lineHeight: '1.65',
    },
    '@media (max-width: 620px)': { '& article': { gridTemplateColumns: '1fr' }, '& article::before': { display: 'none' } },
  }),
  section: css({
    padding: 'clamp(3.5rem, 8vw, 6.25rem) 0',
    scrollMarginTop: '6rem',
    '@media (max-width: 430px)': { scrollMarginTop: '9rem' },
  }),
  sectionHeader: css({
    maxWidth: '52rem',
    marginBottom: '2rem',
    '& p': { ...mutedText, maxWidth: '42rem' },
  }),
  projectGrid: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.12fr) minmax(0, .88fr)',
    gap: '0',
    minWidth: '0',
    borderTop: '1px solid var(--line)',
    borderBottom: '1px solid var(--line)',
    '@media (max-width: 860px)': { gridTemplateColumns: '1fr' },
  }),
  projectCard: css({
    position: 'relative',
    display: 'grid',
    minWidth: '0',
    minHeight: '24rem',
    padding: 'clamp(1.25rem, 3vw, 1.85rem)',
    borderRight: '1px solid var(--line)',
    borderRadius: '0',
    overflow: 'hidden',
    transition: 'transform .24s cubic-bezier(.16,1,.3,1), border-color .24s ease',
    background: 'transparent',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 'auto -20% -42% 18%',
      height: '18rem',
      borderRadius: '999px',
      background: 'radial-gradient(circle, color-mix(in srgb, var(--brand) 18%, transparent), transparent 62%)',
      pointerEvents: 'none',
    },
    '& p': { ...mutedText, position: 'relative' },
    '&:first-child': { minHeight: '30rem' },
    '&:last-child': { borderRight: '0' },
    '@media (max-width: 860px)': {
      minHeight: 'auto',
      borderRight: '0',
      borderBottom: '1px solid var(--line)',
      '&:first-child': { minHeight: 'auto' },
      '&:last-child': { borderBottom: '0' },
    },
  }),
  cardTop: css({
    position: 'relative',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '.75rem',
    marginBottom: 'clamp(2rem, 6vw, 4rem)',
    '@media (max-width: 620px)': { alignItems: 'flex-start', flexDirection: 'column', marginBottom: '1.5rem' },
  }),
  label: css({
    display: 'inline-flex',
    padding: '.38rem .64rem',
    borderRadius: '999px',
    border: '1px solid var(--line)',
    color: 'var(--brand)',
    background: 'color-mix(in srgb, var(--text) 5%, transparent)',
    fontSize: '.76rem',
    fontWeight: '850',
    lineHeight: '1.2',
    whiteSpace: 'nowrap',
  }),
  mutedLabel: css({
    display: 'inline-flex',
    padding: '.38rem .64rem',
    borderRadius: '999px',
    border: '1px solid var(--line)',
    color: 'var(--muted)',
    fontSize: '.76rem',
    fontWeight: '850',
    lineHeight: '1.2',
    whiteSpace: 'nowrap',
  }),
  projectActions: css({
    position: 'relative',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '.46rem',
    marginTop: '1.35rem',
    '& a': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: '0',
      minHeight: '1.78rem',
      padding: '.22rem .92rem .24rem',
      borderRadius: '.68rem',
      border: '1px solid var(--line)',
      color: 'var(--muted)',
      background: 'transparent',
      fontSize: '.78rem',
      fontWeight: '780',
      lineHeight: '1.2',
      whiteSpace: 'nowrap',
      transition: 'transform .2s cubic-bezier(.16,1,.3,1), border-color .2s ease, background .2s ease, color .2s ease',
      _hover: {
        transform: 'translateY(-1px)',
        color: 'var(--text)',
        background: 'color-mix(in srgb, var(--text) 5%, transparent)',
      },
      _active: { transform: 'translateY(1px) scale(.99)' },
      _focusVisible: {
        outline: 'none',
        boxShadow: '0 0 0 4px color-mix(in srgb, var(--brand) 20%, transparent)',
      },
    },
    '& a:first-child': {
      color: 'var(--brand)',
      borderColor: 'color-mix(in srgb, var(--brand) 38%, var(--line))',
      background: 'color-mix(in srgb, var(--brand) 8%, transparent)',
    },
    '@media (max-width: 430px)': {
      gap: '.4rem',
      '& a': {
        minHeight: '1.72rem',
        padding: '.2rem .78rem .22rem',
        fontSize: '.76rem',
      },
    },
  }),
  principlesSection: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, .82fr) minmax(0, 1.18fr)',
    gap: 'clamp(1.4rem, 4vw, 4rem)',
    alignItems: 'start',
    minWidth: '0',
    '@media (max-width: 900px)': { gridTemplateColumns: '1fr' },
  }),
  conversionSection: css({
    scrollMarginTop: '6rem',
  }),
  conversionPanel: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.05fr) minmax(18rem, .95fr)',
    gap: 'clamp(1.5rem, 5vw, 4rem)',
    alignItems: 'start',
    padding: 'clamp(1.25rem, 4vw, 2rem)',
    border: '1px solid color-mix(in srgb, var(--brand) 32%, var(--line))',
    background:
      'linear-gradient(135deg, color-mix(in srgb, var(--brand) 10%, transparent), transparent 58%), color-mix(in srgb, var(--panel-strong) 78%, transparent)',
    boxShadow: 'var(--soft-shadow)',
    '& p': { ...mutedText, maxWidth: '40rem' },
    '@media (max-width: 860px)': {
      gridTemplateColumns: '1fr',
      padding: '1.15rem',
    },
  }),
  conversionList: css({
    display: 'grid',
    gap: '0',
    margin: '0',
    padding: '0',
    listStyle: 'none',
    borderTop: '1px solid var(--line)',
    '& li': {
      display: 'grid',
      gap: '.35rem',
      padding: '1rem 0',
      borderBottom: '1px solid var(--line)',
    },
    '& strong': {
      color: 'var(--text)',
      fontSize: '1.02rem',
      lineHeight: '1.35',
      letterSpacing: '-.02em',
    },
    '& span': {
      color: 'var(--muted)',
      lineHeight: '1.72',
    },
  }),
  stickyText: css({
    position: 'sticky',
    top: '7rem',
    '& p': { ...mutedText, maxWidth: '34rem' },
    '@media (max-width: 900px)': { position: 'relative', top: 'auto' },
  }),
  principleGrid: css({
    display: 'grid',
    gap: '0',
    borderTop: '1px solid var(--line)',
    '& article': {
      display: 'grid',
      gridTemplateColumns: 'minmax(10rem, .45fr) 1fr',
      gap: '1rem',
      padding: '1rem 0',
      borderBottom: '1px solid var(--line)',
      borderRadius: '0',
      background: 'transparent',
    },
    '& p': { ...mutedText, margin: '0' },
    '@media (max-width: 620px)': { '& article': { gridTemplateColumns: '1fr' } },
  }),
  serviceGrid: css({
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '0',
    minWidth: '0',
    marginBottom: '1rem',
    borderTop: '1px solid var(--line)',
    borderLeft: '1px solid var(--line)',
    '& article': { padding: '1.15rem', borderRight: '1px solid var(--line)', borderBottom: '1px solid var(--line)' },
    '& h3': { marginBottom: '.55rem' },
    '& p': { color: 'var(--muted)', lineHeight: '1.72' },
    '@media (max-width: 1020px)': { gridTemplateColumns: 'repeat(2, 1fr)' },
    '@media (max-width: 620px)': { gridTemplateColumns: '1fr' },
  }),
  companyFacts: css({
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '0',
    minWidth: '0',
    margin: '1rem 0 0',
    padding: '0',
    borderTop: '1px solid var(--line)',
    borderLeft: '1px solid var(--line)',
    borderRadius: '0',
    background: 'transparent',
    '& div': { padding: '1rem', borderRight: '1px solid var(--line)', borderBottom: '1px solid var(--line)', borderRadius: '0' },
    '& div:hover': { background: 'color-mix(in srgb, var(--text) 5%, transparent)' },
    '& dt': { color: 'var(--brand)', fontSize: '.82rem', fontWeight: '850' },
    '& dd': { margin: '.38rem 0 0', color: 'var(--muted)', lineHeight: '1.72', overflowWrap: 'anywhere' },
    '@media (max-width: 620px)': { gridTemplateColumns: '1fr' },
  }),
  faqSection: css({ paddingTop: '0' }),
  faqList: css({
    display: 'grid',
    gridTemplateColumns: '1fr 1.15fr .9fr',
    gap: '0',
    minWidth: '0',
    borderTop: '1px solid var(--line)',
    borderLeft: '1px solid var(--line)',
    '& article': { padding: '1.15rem', borderRight: '1px solid var(--line)', borderBottom: '1px solid var(--line)' },
    '& h3': { marginBottom: '.55rem' },
    '& p': { color: 'var(--muted)', lineHeight: '1.72' },
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr' },
  }),
  cta: css({
    position: 'relative',
    display: 'grid',
    gap: '1.4rem',
    margin: '2rem 0 5rem',
    padding: 'clamp(2rem, 6vw, 4rem) 0',
    borderTop: '1px solid var(--line)',
    borderBottom: '1px solid var(--line)',
    borderRadius: '0',
    overflow: 'hidden',
    background: 'transparent',
    '& h2': { maxWidth: '900px', marginBottom: '0' },
    '& p': { ...mutedText, maxWidth: '40rem' },
  }),
  ctaActions: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: '.85rem',
    marginTop: '.2rem',
  }),
  sceneShell: css({
    position: 'relative',
    display: 'grid',
    placeItems: 'center',
    width: '100%',
    maxWidth: '100%',
    minWidth: '0',
    height: '100%',
    minHeight: 'calc(100dvh - 4.5rem)',
    border: '0',
    borderRadius: '0',
    overflow: 'hidden',
    background: 'transparent',
    boxShadow: 'none',
    isolation: 'isolate',
    '&::before': {
      content: '""',
      display: 'none',
      position: 'absolute',
      width: 'min(56vw, 42rem)',
      height: 'min(56vw, 42rem)',
      borderRadius: '999px',
      background:
        'radial-gradient(circle at 50% 50%, color-mix(in srgb, var(--brand) 15%, transparent), transparent 13rem), radial-gradient(circle at 50% 50%, color-mix(in srgb, var(--accent-yellow) 7%, transparent), transparent 19rem)',
      opacity: '.44',
      filter: 'blur(22px) drop-shadow(0 0 30px color-mix(in srgb, var(--brand) 9%, transparent))',
      pointerEvents: 'none',
      zIndex: '0',
      ':root[data-theme="light"] &': {
        opacity: '.25',
        filter: 'blur(18px) drop-shadow(0 0 24px color-mix(in srgb, var(--brand) 8%, transparent))',
      },
    },
    '&::after': {
      content: '""',
      display: 'none',
      position: 'absolute',
      width: 'min(38vw, 29rem)',
      height: 'min(38vw, 29rem)',
      borderRadius: '999px',
      border: '1px solid color-mix(in srgb, var(--text) 8%, transparent)',
      background:
        'repeating-conic-gradient(from -10deg, color-mix(in srgb, var(--text) 20%, transparent) 0 .45deg, transparent .45deg 8deg), radial-gradient(circle, transparent 52%, color-mix(in srgb, var(--brand) 18%, transparent) 53% 54%, transparent 55% 64%, color-mix(in srgb, var(--text) 14%, transparent) 65% 66%, transparent 67%)',
      opacity: '.075',
      pointerEvents: 'none',
      zIndex: '0',
      ':root[data-theme="light"] &': {
        borderColor: 'color-mix(in srgb, var(--text) 12%, transparent)',
        opacity: '.11',
      },
    },
    '&[data-scene-status=ready] [data-scene-fallback]': {
      opacity: '0',
      transform: 'translate(-50%, -50%) scale(.92) rotateX(58deg)',
      animation: 'none',
    },
    '&[data-scene-status=fallback] [data-scene-fallback]': {
      opacity: '.2',
      transform: 'translate(-50%, -50%) scale(.92) rotateX(58deg)',
      animation: 'none',
    },
    '@media (max-width: 980px)': {
      height: '100%',
      minHeight: '0',
    },
  }),
  sceneCanvas: css({
    position: 'absolute',
    inset: '0',
    width: '100%',
    height: '100%',
    display: 'block',
    zIndex: '1',
  }),
  sceneOverlay: css({
    position: 'absolute',
    inset: '0',
    pointerEvents: 'none',
    background: 'transparent',
    zIndex: '2',
  }),
  sceneFallback: css({
    position: 'absolute',
    left: '50%',
    top: '50%',
    width: 'min(42vw, 31rem)',
    minWidth: '22rem',
    aspectRatio: '1',
    borderRadius: '999px',
    border: '1px solid color-mix(in srgb, var(--brand) 48%, transparent)',
    opacity: '0',
    transform: 'translate(-50%, -50%) rotateX(58deg) rotateZ(-18deg)',
    transformStyle: 'preserve-3d',
    transition: 'opacity .32s ease, transform .32s ease',
    pointerEvents: 'none',
    zIndex: '0',
    background:
      'radial-gradient(circle at 50% 50%, transparent 0 22%, color-mix(in srgb, var(--brand) 26%, transparent) 23% 24%, transparent 25% 40%, color-mix(in srgb, var(--accent-yellow) 20%, transparent) 41% 42%, transparent 43% 62%, color-mix(in srgb, var(--brand) 34%, transparent) 63% 64%, transparent 65%), conic-gradient(from 20deg, color-mix(in srgb, var(--brand) 72%, transparent), transparent 8%, color-mix(in srgb, var(--accent-yellow) 72%, transparent) 16%, transparent 24%, color-mix(in srgb, var(--accent-green) 54%, transparent) 34%, transparent 48%, color-mix(in srgb, var(--brand) 64%, transparent) 60%, transparent 76%, color-mix(in srgb, var(--accent-blue) 50%, transparent) 86%, transparent)',
    filter: 'drop-shadow(0 0 28px color-mix(in srgb, var(--brand) 28%, transparent))',
    animation: 'none',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: '29%',
      borderRadius: '28%',
      border: '1px solid color-mix(in srgb, var(--accent-yellow) 62%, transparent)',
      background:
        'linear-gradient(135deg, color-mix(in srgb, var(--brand) 22%, transparent), transparent), color-mix(in srgb, var(--bg) 30%, transparent)',
      transform: 'translateZ(32px) rotateZ(45deg)',
      boxShadow: '0 0 26px color-mix(in srgb, var(--accent-yellow) 24%, transparent)',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      inset: '8%',
      borderRadius: '999px',
      border: '1px dashed color-mix(in srgb, var(--text) 22%, transparent)',
      transform: 'translateZ(18px)',
    },
    '@media (max-width: 980px)': {
      width: 'min(72vw, 26rem)',
      minWidth: '15rem',
    },
  }),
  scenePlate: css({
    position: 'absolute',
    left: 'clamp(1rem, 5vw, 4rem)',
    bottom: 'clamp(1rem, 6vw, 4.5rem)',
    display: 'grid',
    gap: '.42rem',
    maxWidth: '24rem',
    pointerEvents: 'none',
    zIndex: '3',
    '& strong': {
      display: 'block',
      maxWidth: '20rem',
      color: 'var(--text)',
      fontSize: 'clamp(.98rem, 1.5vw, 1.16rem)',
      lineHeight: '1.36',
      letterSpacing: '-.025em',
    },
    '& span': { display: 'block', color: 'var(--muted)', fontSize: '.84rem', lineHeight: '1.55' },
    '@media (max-width: 980px)': { display: 'none' },
  }),
  sceneCodePanel: css({
    position: 'absolute',
    right: 'clamp(1rem, 4.8vw, 4rem)',
    bottom: 'clamp(5.2rem, 9vw, 6.5rem)',
    display: 'none',
    width: 'min(22rem, 31vw)',
    minHeight: '7rem',
    pointerEvents: 'none',
    zIndex: '3',
    '& pre': {
      position: 'absolute',
      inset: '0',
      margin: '0',
      padding: '.9rem 1rem',
      borderRadius: '.82rem',
      border: '1px solid color-mix(in srgb, var(--text) 10%, transparent)',
      background: 'color-mix(in srgb, var(--bg) 78%, transparent)',
      boxShadow: 'inset 0 1px color-mix(in srgb, var(--text) 7%, transparent), 0 18px 45px rgba(0,0,0,.18)',
      backdropFilter: 'blur(12px)',
      opacity: '0',
      transform: 'translateY(10px)',
    },
    '& pre:first-child': { opacity: '1', transform: 'translateY(0)' },
    '& code': {
      color: 'var(--text)',
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      fontSize: '.78rem',
      lineHeight: '1.55',
      whiteSpace: 'pre-wrap',
    },
    '@media (max-width: 980px)': { display: 'none' },
  }),
  sceneScrub: css({
    position: 'absolute',
    left: '50%',
    right: 'auto',
    bottom: 'clamp(1.1rem, 3vw, 2rem)',
    display: 'grid',
    gridTemplateColumns: 'auto minmax(8rem, 16rem)',
    gap: '.75rem',
    alignItems: 'center',
    transform: 'translateX(-50%)',
    pointerEvents: 'none',
    zIndex: '3',
    '& > span': {
      color: 'var(--muted)',
      fontSize: '.68rem',
      fontWeight: '850',
      letterSpacing: '.16em',
      textTransform: 'uppercase',
      whiteSpace: 'nowrap',
    },
    '& i': {
      position: 'relative',
      display: 'block',
      height: '.62rem',
      borderRadius: '999px',
      overflow: 'hidden',
      background: 'repeating-linear-gradient(90deg, color-mix(in srgb, var(--text) 18%, transparent) 0 .08rem, transparent .08rem .28rem), color-mix(in srgb, var(--text) 7%, transparent)',
      boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--text) 7%, transparent)',
    },
    '& i span': {
      position: 'absolute',
      inset: '0',
      display: 'block',
      borderRadius: 'inherit',
      background: 'linear-gradient(90deg, var(--accent-red), var(--accent-yellow), var(--accent-green), var(--accent-blue))',
      transform: 'scaleX(.08)',
      transformOrigin: 'left center',
    },
    '@media (max-width: 980px)': { display: 'none' },
  }),
  sceneSignal: css({
    width: 'fit-content',
    padding: '.34rem .58rem',
    borderRadius: '999px',
    border: '1px solid color-mix(in srgb, var(--brand) 35%, var(--line))',
    color: 'var(--brand)!important',
    background: 'color-mix(in srgb, var(--bg) 58%, transparent)',
    fontSize: '.68rem!important',
    fontWeight: '850',
    letterSpacing: '.13em',
    lineHeight: '1.2!important',
    textTransform: 'uppercase',
  }),
};
