import { css } from '../styled-system/css';

const mutedText = {
  color: 'var(--muted)',
  lineHeight: '1.75',
};

export const layoutStyles = {
  noise: css({
    pointerEvents: 'none',
    position: 'fixed',
    inset: '0',
    zIndex: '60',
    opacity: '.055',
    mixBlendMode: 'overlay',
    backgroundImage:
      'linear-gradient(rgba(255,255,255,.12) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.12) 1px, transparent 1px)',
    backgroundSize: '40px 40px',
  }),
  header: css({
    position: 'sticky',
    top: '0',
    zIndex: '20',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    minHeight: '4.5rem',
    padding: 'max(.72rem, env(safe-area-inset-top)) clamp(1rem, 4vw, 4rem) .72rem',
    borderBottom: '1px solid var(--line)',
    background: 'var(--header-bg)',
    backdropFilter: 'blur(12px)',
    '@media (max-width: 720px)': {
      alignItems: 'flex-start',
      flexDirection: 'column',
      minHeight: 'auto',
      gap: '.75rem',
    },
  }),
  brand: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '.78rem',
    minWidth: 'max-content',
    '& strong, & small': { display: 'block' },
    '& strong': { letterSpacing: '-.02em' },
    '& small': { color: 'var(--muted)', fontSize: '.7rem', letterSpacing: '.14em' },
  }),
  brandMark: css({
    display: 'grid',
    placeItems: 'center',
    width: '2.55rem',
    height: '2.55rem',
    border: '1px solid color-mix(in srgb, var(--brand) 55%, transparent)',
    borderRadius: '.72rem',
    color: 'var(--brand)',
    background: 'linear-gradient(135deg, color-mix(in srgb, var(--brand) 18%, transparent), color-mix(in srgb, var(--text) 6%, transparent))',
    boxShadow: '0 0 22px color-mix(in srgb, var(--brand) 14%, transparent)',
    fontWeight: '900',
    '@media (max-width: 430px)': { width: '2.35rem', height: '2.35rem', borderRadius: '.82rem' },
  }),
  headerTools: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '.65rem',
    minWidth: '0',
    '@media (max-width: 720px)': {
      width: '100%',
      alignItems: 'stretch',
      justifyContent: 'space-between',
      gap: '.6rem',
    },
    '@media (max-width: 430px)': { flexDirection: 'column' },
  }),
  nav: css({
    display: 'flex',
    gap: '.28rem',
    '& a': {
      padding: '.62rem .82rem',
      borderRadius: '.7rem',
      color: 'var(--muted)',
      fontSize: '.94rem',
      lineHeight: '1.2',
      whiteSpace: 'nowrap',
      transition: 'color .18s ease, background .18s ease',
    },
    '& a:hover, & a:focus-visible': {
      color: 'var(--text)',
      background: 'color-mix(in srgb, var(--text) 7%, transparent)',
      outline: 'none',
    },
    '@media (max-width: 720px)': {
      minWidth: '0',
      overflowX: 'auto',
      scrollbarWidth: 'none',
      paddingBottom: '.1rem',
      '&::-webkit-scrollbar': { display: 'none' },
      '& a': { padding: '.6rem .74rem', fontSize: '.9rem' },
    },
    '@media (max-width: 430px)': { width: '100%' },
  }),
  themeToggle: css({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '.45rem',
    minHeight: '2.55rem',
    padding: '.54rem .78rem',
    border: '1px solid var(--line)',
    borderRadius: '999px',
    color: 'var(--text)',
    background: 'var(--panel)',
    boxShadow: 'inset 0 1px rgba(245,240,231,.08)',
    cursor: 'pointer',
    _hover: { borderColor: 'color-mix(in srgb, var(--brand) 55%, var(--line))' },
    _focusVisible: {
      outline: 'none',
      borderColor: 'color-mix(in srgb, var(--brand) 55%, var(--line))',
      boxShadow: '0 0 0 4px color-mix(in srgb, var(--brand) 18%, transparent)',
    },
    '@media (max-width: 720px)': { flex: '0 0 auto', paddingInline: '.72rem' },
    '@media (max-width: 430px)': { width: '100%' },
  }),
  themeToggleOrb: css({
    width: '.78rem',
    height: '.78rem',
    borderRadius: '999px',
    background: 'linear-gradient(135deg, var(--brand), var(--brand-strong))',
    boxShadow: '0 0 18px color-mix(in srgb, var(--brand) 35%, transparent)',
  }),
  footer: css({
    display: 'flex',
    justifyContent: 'space-between',
    gap: '1rem',
    padding: '2rem clamp(1rem, 4vw, 4rem) calc(2rem + env(safe-area-inset-bottom))',
    borderTop: '1px solid var(--line)',
    background: 'var(--footer-bg)',
    '& p': { ...mutedText, margin: '.35rem 0 0', fontSize: '.92rem' },
    '& code': { color: 'var(--brand)' },
    '@media (max-width: 980px)': { flexDirection: 'column' },
  }),
};
