import { css } from '../styled-system/css';

const panel = {
  border: '1px solid var(--line)',
  background: 'var(--panel)',
  boxShadow: 'inset 0 1px rgba(255,255,255,.06)',
  backdropFilter: 'blur(18px)',
};

const mutedText = {
  color: 'var(--muted)',
  lineHeight: '1.86',
};

const pillAction = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: '3rem',
  padding: '.85rem 1.2rem',
  borderRadius: '999px',
  border: '1px solid var(--line)',
  fontWeight: '850',
  lineHeight: '1.25',
  transition: 'transform .18s ease, border-color .18s ease, background .18s ease',
  _hover: { transform: 'translateY(-2px)' },
  '@media (max-width: 720px)': { width: '100%' },
};

export const layoutStyles = {
  noise: css({
    pointerEvents: 'none',
    position: 'fixed',
    inset: '0',
    opacity: '.055',
    mixBlendMode: 'soft-light',
    backgroundImage: 'linear-gradient(rgba(255,255,255,.12) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.12) 1px, transparent 1px)',
    backgroundSize: '36px 36px',
  }),
  header: css({
    position: 'sticky',
    top: '0',
    zIndex: '10',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    padding: 'max(.85rem, env(safe-area-inset-top)) clamp(1rem, 4vw, 4rem) .85rem',
    borderBottom: '1px solid var(--line)',
    background: 'var(--header-bg)',
    backdropFilter: 'blur(18px)',
    '@media (max-width: 720px)': { alignItems: 'flex-start', flexDirection: 'column', gap: '.8rem' },
  }),
  brand: css({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '.8rem',
    minWidth: 'max-content',
    '& strong, & small': { display: 'block' },
    '& small': { color: 'var(--muted)', fontSize: '.7rem', letterSpacing: '.24em' },
  }),
  brandMark: css({
    display: 'grid',
    placeItems: 'center',
    width: '2.6rem',
    height: '2.6rem',
    border: '1px solid color-mix(in srgb, var(--brand) 58%, transparent)',
    borderRadius: '.9rem',
    color: 'var(--brand)',
    background: 'linear-gradient(135deg, color-mix(in srgb, var(--brand) 14%, transparent), color-mix(in srgb, var(--hot) 12%, transparent))',
    boxShadow: '0 0 30px color-mix(in srgb, var(--brand) 18%, transparent)',
    fontWeight: '900',
    '@media (max-width: 430px)': { width: '2.35rem', height: '2.35rem', borderRadius: '.8rem' },
  }),
  headerTools: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '.65rem',
    minWidth: '0',
    '@media (max-width: 720px)': { width: '100%', alignItems: 'stretch', justifyContent: 'space-between', gap: '.6rem' },
    '@media (max-width: 430px)': { flexDirection: 'column' },
  }),
  nav: css({
    display: 'flex',
    gap: '.35rem',
    '& a': { padding: '.65rem .85rem', borderRadius: '999px', color: 'var(--muted)', fontSize: '.94rem', whiteSpace: 'nowrap' },
    '& a:hover, & a:focus-visible': { color: 'var(--text)', background: 'color-mix(in srgb, var(--text) 7%, transparent)' },
    '@media (max-width: 720px)': {
      minWidth: '0',
      overflowX: 'auto',
      scrollbarWidth: 'none',
      paddingBottom: '.1rem',
      '&::-webkit-scrollbar': { display: 'none' },
      '& a': { padding: '.62rem .78rem', fontSize: '.9rem' },
    },
    '@media (max-width: 430px)': { width: '100%' },
  }),
  themeToggle: css({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '.45rem',
    minHeight: '2.6rem',
    padding: '.55rem .78rem',
    border: '1px solid var(--line)',
    borderRadius: '999px',
    color: 'var(--text)',
    background: 'var(--panel)',
    boxShadow: 'inset 0 1px rgba(255,255,255,.08)',
    cursor: 'pointer',
    _hover: { borderColor: 'color-mix(in srgb, var(--brand) 55%, var(--line))' },
    _focusVisible: { borderColor: 'color-mix(in srgb, var(--brand) 55%, var(--line))' },
    '@media (max-width: 720px)': { flex: '0 0 auto', paddingInline: '.7rem' },
    '@media (max-width: 430px)': { width: '100%' },
  }),
  themeToggleOrb: css({
    width: '.78rem',
    height: '.78rem',
    borderRadius: '999px',
    background: 'linear-gradient(135deg, var(--brand), var(--hot))',
    boxShadow: '0 0 18px color-mix(in srgb, var(--brand) 35%, transparent)',
  }),
  footer: css({
    display: 'flex',
    justifyContent: 'space-between',
    gap: '1rem',
    padding: '2rem clamp(1rem, 4vw, 4rem) calc(2rem + env(safe-area-inset-bottom))',
    borderTop: '1px solid var(--line)',
    background: 'var(--footer-bg)',
    '& p': { ...mutedText, margin: '.35rem 0 0', fontSize: '.92rem' },
    '& code': { color: 'var(--brand)' },
    '@media (max-width: 980px)': { flexDirection: 'column' },
  }),
};

export const pageStyles = {
  main: css({ width: 'min(var(--content-width), calc(100% - 2rem))', margin: '0 auto', '@media (max-width: 720px)': { width: 'min(100% - 1.25rem, var(--content-width))' } }),
  sectionGrid: css({
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.04fr) minmax(320px, .96fr)',
    gap: 'clamp(1.5rem, 4vw, 4rem)',
    alignItems: 'center',
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr' },
  }),
  hero: css({ minHeight: '78vh', padding: 'clamp(4rem, 8vw, 6.5rem) 0 3rem', '@media (max-width: 980px)': { minHeight: 'auto' }, '@media (max-width: 720px)': { paddingTop: '3rem' } }),
  eyebrow: css({ margin: '0 0 1rem', color: 'var(--brand)', fontSize: '.78rem', fontWeight: '850', lineHeight: '1.6', letterSpacing: '.16em', textTransform: 'uppercase' }),
  h1: css({ marginBottom: '1.35rem', maxWidth: '10ch', fontSize: 'clamp(3rem, 8vw, 7rem)', lineHeight: '1.08', letterSpacing: '-.075em', '& span': { display: 'block', color: 'transparent', background: 'linear-gradient(90deg, var(--brand), var(--brand-strong), var(--hot))', backgroundClip: 'text' }, '@media (max-width: 980px)': { maxWidth: '12ch' }, '@media (max-width: 720px)': { fontSize: 'clamp(2.7rem, 15vw, 4.6rem)', lineHeight: '1.1', letterSpacing: '-.065em' } }),
  h2: css({ fontSize: 'clamp(2rem, 5vw, 4.2rem)', lineHeight: '1.18', letterSpacing: '-.055em', '@media (max-width: 720px)': { lineHeight: '1.2', letterSpacing: '-.045em' } }),
  h3: css({ fontSize: 'clamp(1.25rem, 2vw, 1.5rem)', lineHeight: '1.35', letterSpacing: '-.025em' }),
  bodyText: css({ ...mutedText }),
  heroText: css({ ...mutedText, maxWidth: '44rem', fontSize: 'clamp(1rem, 1.8vw, 1.12rem)' }),
  actionRow: css({ display: 'flex', flexWrap: 'wrap', gap: '.9rem', marginTop: '2rem', '@media (max-width: 430px)': { gap: '.7rem' } }),
  buttonPrimary: css({ ...pillAction, borderColor: 'transparent', color: 'var(--ink-on-brand)', background: 'linear-gradient(135deg, var(--brand), var(--brand-strong))' }),
  buttonGhost: css({ ...pillAction, color: 'var(--text)', background: 'color-mix(in srgb, var(--text) 6%, transparent)' }),
  heroVisual: css({ position: 'relative', display: 'grid', gap: '1rem', minWidth: '0', '@media (max-width: 980px)': { maxWidth: '42rem', width: '100%', margin: '0 auto' } }),
  modelStage: css({
    position: 'relative',
    display: 'grid',
    placeItems: 'center',
    minHeight: 'clamp(22rem, 42vw, 34rem)',
    border: '1px solid var(--line)',
    borderRadius: 'clamp(1.5rem, 4vw, 2.5rem)',
    overflow: 'hidden',
    background: 'radial-gradient(circle at 50% 42%, color-mix(in srgb, var(--brand) 18%, transparent), transparent 15rem), radial-gradient(circle at 58% 58%, color-mix(in srgb, var(--hot) 18%, transparent), transparent 17rem), linear-gradient(180deg, color-mix(in srgb, var(--panel-strong) 80%, transparent), color-mix(in srgb, var(--panel) 84%, transparent))',
    boxShadow: 'var(--shadow), inset 0 1px rgba(255,255,255,.08)',
    perspective: '900px',
    isolation: 'isolate',
    '@media (max-width: 720px)': { minHeight: '24rem' },
    '@media (max-width: 430px)': { minHeight: '21rem' },
  }),
  modelGrid: css({ position: 'absolute', inset: '14% -10% -22%', transform: 'rotateX(68deg) rotateZ(-16deg)', transformOrigin: 'center', backgroundImage: 'linear-gradient(color-mix(in srgb, var(--brand) 25%, transparent) 1px, transparent 1px), linear-gradient(90deg, color-mix(in srgb, var(--brand) 25%, transparent) 1px, transparent 1px)', backgroundSize: '2.6rem 2.6rem', opacity: '.38', maskImage: 'linear-gradient(to top, transparent, #000 22%, #000 72%, transparent)' }),
  orbitOne: css({ position: 'absolute', width: 'min(72%, 21rem)', aspectRatio: '1', border: '1px solid color-mix(in srgb, var(--brand) 48%, transparent)', borderRadius: '50%', transformStyle: 'preserve-3d', animation: 'orbit-spin 12s linear infinite', transform: 'rotateX(68deg) rotateZ(18deg)' }),
  orbitTwo: css({ position: 'absolute', width: 'min(58%, 17rem)', aspectRatio: '1', border: '1px solid color-mix(in srgb, var(--hot) 44%, transparent)', borderRadius: '50%', transformStyle: 'preserve-3d', animation: 'orbit-spin 15s linear infinite reverse', transform: 'rotateX(64deg) rotateZ(-30deg)' }),
  coreCube: css({ position: 'relative', width: 'clamp(6.8rem, 16vw, 9.4rem)', height: 'clamp(6.8rem, 16vw, 9.4rem)', transformStyle: 'preserve-3d', transform: 'rotateX(-18deg) rotateY(34deg)', animation: 'cube-float 7s ease-in-out infinite', zIndex: '2' }),
  cubeFace: css({ position: 'absolute', inset: '0', display: 'grid', placeItems: 'center', border: '1px solid color-mix(in srgb, var(--brand) 56%, transparent)', background: 'linear-gradient(135deg, color-mix(in srgb, var(--brand) 24%, transparent), color-mix(in srgb, var(--hot) 14%, transparent)), var(--panel-strong)', color: 'var(--text)', fontSize: 'clamp(.78rem, 2vw, 1rem)', fontWeight: '950', letterSpacing: '.12em', boxShadow: 'inset 0 1px rgba(255,255,255,.16), 0 0 30px color-mix(in srgb, var(--brand) 18%, transparent)', backfaceVisibility: 'hidden' }),
  faceFront: css({ transform: 'translateZ(calc(clamp(6.8rem, 16vw, 9.4rem) / 2))' }),
  faceBack: css({ transform: 'rotateY(180deg) translateZ(calc(clamp(6.8rem, 16vw, 9.4rem) / 2))' }),
  faceRight: css({ transform: 'rotateY(90deg) translateZ(calc(clamp(6.8rem, 16vw, 9.4rem) / 2))' }),
  faceLeft: css({ transform: 'rotateY(-90deg) translateZ(calc(clamp(6.8rem, 16vw, 9.4rem) / 2))' }),
  faceTop: css({ transform: 'rotateX(90deg) translateZ(calc(clamp(6.8rem, 16vw, 9.4rem) / 2))' }),
  faceBottom: css({ transform: 'rotateX(-90deg) translateZ(calc(clamp(6.8rem, 16vw, 9.4rem) / 2))' }),
  modelNodes: css({ position: 'absolute', inset: '1.2rem', zIndex: '3', pointerEvents: 'none', '& span': { position: 'absolute', display: 'inline-flex', alignItems: 'center', minHeight: '2.25rem', padding: '.55rem .75rem', border: '1px solid var(--line)', borderRadius: '999px', color: 'var(--text)', background: 'color-mix(in srgb, var(--panel-strong) 84%, transparent)', boxShadow: 'var(--soft-shadow)', fontSize: 'clamp(.72rem, 1.8vw, .86rem)', fontWeight: '850', lineHeight: '1.25' }, '& span:nth-child(1)': { top: '7%', left: '7%' }, '& span:nth-child(2)': { top: '18%', right: '5%' }, '& span:nth-child(3)': { bottom: '17%', left: '4%' }, '& span:nth-child(4)': { right: '7%', bottom: '8%', color: 'var(--brand)' }, '@media (max-width: 430px)': { inset: '.75rem', '& span': { padding: '.48rem .62rem' } } }),
  terminal: css({ border: '1px solid var(--line)', borderRadius: '1.6rem', background: 'linear-gradient(180deg, color-mix(in srgb, var(--panel-strong) 95%, #000 5%), color-mix(in srgb, var(--panel) 88%, #000 12%))', boxShadow: 'var(--shadow), inset 0 1px rgba(255,255,255,.08)', overflow: 'hidden', position: 'relative', zIndex: '4', width: 'min(92%, 28rem)', margin: '-5.5rem auto 0', transform: 'rotate(1deg)', '& pre': { margin: '0', padding: '1.2rem', overflowX: 'auto' }, '& code': { color: 'color-mix(in srgb, var(--brand-strong) 78%, var(--text))', fontFamily: '"SFMono-Regular", Consolas, ui-monospace, monospace', lineHeight: '1.7' }, '@media (max-width: 720px)': { width: '100%', marginTop: '-3rem', transform: 'none', '& pre': { padding: '1rem', fontSize: '.78rem' } } }),
  terminalBar: css({ display: 'flex', gap: '.45rem', padding: '1rem', borderBottom: '1px solid var(--line)', '& span': { width: '.75rem', height: '.75rem', borderRadius: '999px', background: 'var(--hot)' }, '& span:nth-child(2)': { background: 'var(--warn)' }, '& span:nth-child(3)': { background: 'var(--brand)' } }),
  metrics: css({ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', margin: '0 0 clamp(4rem, 7vw, 6rem)', '& article': { ...panel, padding: '1.1rem', borderRadius: '1.2rem', minWidth: '0' }, '& strong, & span': { display: 'block' }, '& strong': { color: 'var(--brand)', fontSize: '1.05rem', lineHeight: '1.35' }, '& span': { color: 'var(--muted)', marginTop: '.35rem', fontSize: '.9rem', lineHeight: '1.55' }, '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, 1fr)' }, '@media (max-width: 720px)': { gridTemplateColumns: '1fr' } }),
  section: css({ padding: '3rem 0 clamp(4rem, 7vw, 6rem)', scrollMarginTop: '6rem', '@media (max-width: 430px)': { scrollMarginTop: '9rem' } }),
  sectionHeading: css({ maxWidth: '780px', marginBottom: '2rem', '& p': mutedText }),
  projectGrid: css({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr)', gap: '1rem' }),
  projectCard: css({ ...panel, minHeight: '18rem', padding: 'clamp(1.15rem, 3vw, 1.55rem)', borderRadius: '1.5rem', transition: 'transform .2s ease, border-color .2s ease, background .2s ease', background: 'linear-gradient(135deg, color-mix(in srgb, var(--brand) 16%, transparent), color-mix(in srgb, var(--hot) 10%, transparent)), var(--panel-strong)', _hover: { transform: 'translateY(-4px)', borderColor: 'color-mix(in srgb, var(--brand) 55%, transparent)' }, '& p': mutedText }),
  cardTop: css({ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '.75rem', marginBottom: '2.2rem', '@media (max-width: 720px)': { marginBottom: '1.4rem' } }),
  tag: css({ display: 'inline-flex', padding: '.35rem .6rem', borderRadius: '999px', border: '1px solid var(--line)', color: 'var(--brand)', fontSize: '.72rem', fontWeight: '900', lineHeight: '1.2', letterSpacing: '.08em', textTransform: 'uppercase', whiteSpace: 'nowrap' }),
  status: css({ display: 'inline-flex', padding: '.35rem .6rem', borderRadius: '999px', border: '1px solid var(--line)', color: 'var(--warn)', fontSize: '.72rem', fontWeight: '900', lineHeight: '1.2', letterSpacing: '.08em', textTransform: 'uppercase', whiteSpace: 'nowrap' }),
  projectActions: css({ display: 'flex', flexWrap: 'wrap', gap: '.9rem', marginTop: '2rem', '& a': { ...pillAction, color: 'var(--text)', background: 'color-mix(in srgb, var(--text) 6%, transparent)' }, '& a:first-child': { color: 'var(--ink-on-brand)', background: 'linear-gradient(135deg, var(--brand), var(--brand-strong))', borderColor: 'transparent' }, '@media (max-width: 720px)': { gap: '.7rem' } }),
  split: css({ display: 'grid', gridTemplateColumns: 'minmax(0, 1.04fr) minmax(320px, .96fr)', gap: 'clamp(1.5rem, 4vw, 4rem)', alignItems: 'start', '@media (max-width: 980px)': { gridTemplateColumns: '1fr' } }),
  principles: css({ display: 'grid', gap: '.9rem', '& > div': { ...panel, padding: '1.1rem', borderRadius: '1.2rem' }, '& strong': { lineHeight: '1.45' }, '& p': { ...mutedText, margin: '.5rem 0 0' } }),
  seoGrid: css({ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', marginBottom: '1rem', '& article': { ...panel, padding: '1.15rem', borderRadius: '1.25rem' }, '& h3': { marginBottom: '.55rem' }, '& p': { color: 'var(--muted)', lineHeight: '1.78' }, '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, 1fr)' }, '@media (max-width: 720px)': { gridTemplateColumns: '1fr' } }),
  companyFacts: css({ ...panel, display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0', margin: '1rem 0 0', padding: '.35rem', borderRadius: '1.35rem', '& div': { padding: '1rem', borderRadius: '1rem' }, '& div:hover': { background: 'color-mix(in srgb, var(--text) 5%, transparent)' }, '& dt': { color: 'var(--brand)', fontSize: '.78rem', fontWeight: '900', letterSpacing: '.12em', textTransform: 'uppercase' }, '& dd': { margin: '.4rem 0 0', color: 'var(--muted)', lineHeight: '1.78' }, '@media (max-width: 720px)': { gridTemplateColumns: '1fr' } }),
  faqSection: css({ paddingTop: '0' }),
  faqList: css({ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', '& article': { ...panel, padding: '1.15rem', borderRadius: '1.25rem' }, '& h3': { marginBottom: '.55rem' }, '& p': { color: 'var(--muted)', lineHeight: '1.78' }, '@media (max-width: 980px)': { gridTemplateColumns: 'repeat(2, 1fr)' }, '@media (max-width: 720px)': { gridTemplateColumns: '1fr' } }),
  cta: css({ ...panel, margin: '2rem 0 5rem', padding: 'clamp(2rem, 6vw, 4rem)', borderRadius: '2rem', background: 'radial-gradient(circle at top right, color-mix(in srgb, var(--brand) 20%, transparent), transparent 24rem), linear-gradient(135deg, color-mix(in srgb, var(--text) 8%, transparent), color-mix(in srgb, var(--text) 3%, transparent))', '& h2': { maxWidth: '920px', marginBottom: '0' }, '@media (max-width: 720px)': { borderRadius: '1.5rem' } }),
};
